import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useNotify } from '../context/NotificationContext';
import { Calendar, Users, Download, Filter, Search, User, Clock, MapPin } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import companyLogo from './Transparent logo.png?inline';

const addPdfHeader = (doc, title) => {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(245, 248, 252);
  doc.rect(0, 0, pageWidth, 38, 'F');

  try {
    doc.addImage(companyLogo, 'PNG', 14, 8, 20, 20);
  } catch (error) {
    console.warn('Unable to add logo to attendance PDF:', error);
  }

  doc.setFontSize(20);
  doc.setTextColor(40, 40, 40);
  doc.text(title, pageWidth / 2, 22, { align: 'center' });
};

const AttendanceManagement = () => {
  const { user } = useAuth();
  const { showNotification } = useNotify();
  const [view, setView] = useState('status'); // 'status' or 'logs'
  const [attendance, setAttendance] = useState([]);
  const [dailyStatus, setDailyStatus] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [dateFilter, setDateFilter] = useState('');
  const [branches, setBranches] = useState([]);
  const [branchFilter, setBranchFilter] = useState('all');

  useEffect(() => {
    fetchBranches();
  }, []);

  useEffect(() => {
    if (view === 'logs') fetchAttendance();
    else fetchDailyStatus();
  }, [view, branchFilter]);

  const fetchBranches = async () => {
    try {
      const res = await fetch('/api/auth/branches');
      const data = await res.json();
      setBranches(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error('Failed to fetch branches:', err);
    }
  };

  const fetchAttendance = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ role: user.role });
      if (branchFilter && branchFilter !== 'all') params.append('branch', branchFilter);
      const response = await fetch(`/api/attendance/all?${params}`);
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Failed to fetch');
      setAttendance(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error("Failed to fetch attendance:", err);
      showNotification(err.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  const fetchDailyStatus = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ role: user.role });
      if (branchFilter && branchFilter !== 'all') params.append('branch', branchFilter);
      const response = await fetch(`/api/attendance/daily-status?${params}`);
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Failed to fetch status');
      setDailyStatus(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error("Failed to fetch daily status:", err);
      showNotification(err.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  const filteredData = view === 'logs'
  ? attendance.filter(log => {

      const role =
        (
          log.employee_role ||
          log.role ||
          ''
        ).toLowerCase();

      // REMOVE HR & ADMIN
      if (
        role === 'admin' ||
        role === 'hr'
      ) {
        return false;
      }

      const matchesSearch =
        (log.employee_name || '')
          .toLowerCase()
          .includes(searchTerm.toLowerCase());

      const matchesDate =
        dateFilter === '' ||
        (log.date || '')
          .includes(dateFilter);

      return (
        matchesSearch &&
        matchesDate
      );
    })

  : dailyStatus.filter(emp => {

      const role =
        (
          emp.employee_role ||
          emp.role ||
          ''
        ).toLowerCase();

      // REMOVE HR & ADMIN
      if (
        role === 'admin' ||
        role === 'hr'
      ) {
        return false;
      }

      return (
        (emp.name || '')
          .toLowerCase()
          .includes(searchTerm.toLowerCase())
      );
    });

  // Stats for summary
  const presentCount = dailyStatus.filter(e => e.status === 'Present').length;
  const absentCount = dailyStatus.filter(e => e.status === 'Absent').length;

  const handleExportPDF = () => {
    if (user.role !== 'admin' && user.role !== 'hr') {
      showNotification('Only Admin and HR can export attendance reports', 'warning');
      return;
    }

    const doc = new jsPDF();
    addPdfHeader(doc, view === 'logs' ? 'Attendance History Report' : 'Daily Attendance Status');
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by: ${user.name} (${user.role.toUpperCase()})`, 14, 48);
    doc.text(`Date: ${new Date().toLocaleString()}`, 14, 53);
    if (branchFilter !== 'all') doc.text(`Branch Filter: ${branchFilter}`, 14, 58);

    const tableColumn = view === 'logs' 
      ? ["Date", "Employee Name", "Role", "Department", "Branch", "Time"]
      : ["Employee Name", "Role", "Department", "Branch", "Status", "Time"];

    const tableRows = view === 'logs'
      ? filteredData.map(log => [
          new Date(log.date).toLocaleDateString(),
          log.employee_name,
          log.employee_role.toUpperCase(),
          log.department,
          log.branch || '—',
          log.created_at ? new Date(log.created_at).toLocaleTimeString() : 'N/A'
        ])
      : filteredData.map(emp => [
          emp.name,
          emp.employee_role.toUpperCase(),
          emp.department,
          emp.branch || '—',
          emp.status,
          emp.clock_in_time ? new Date(emp.clock_in_time).toLocaleTimeString() : '-'
        ]);

    doc.autoTable({
      startY: branchFilter !== 'all' ? 66 : 61,
      head: [tableColumn],
      body: tableRows,
      theme: 'striped',
      headStyles: { fillColor: view === 'logs' ? [59, 130, 246] : [16, 185, 129] }
    });

    doc.save(`${view === 'logs' ? 'Attendance_Logs' : 'Daily_Status'}_${new Date().toISOString().split('T')[0]}.pdf`);
    showNotification('Report exported successfully', 'success');
  };

  return (
    <div className="main-content">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1>Attendance Management</h1>
          <p>{view === 'status' ? "Real-time daily presence monitoring" : "Historical clock-in records"}</p>
        </div>
        <div style={{ display: 'flex', gap: '1rem' }}>
          {(user.role === 'admin' || user.role === 'hr') && (
            <button className="btn" onClick={handleExportPDF} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <Download size={18} /> Export PDF
            </button>
          )}
          <button className="btn btn-secondary" onClick={view === 'logs' ? fetchAttendance : fetchDailyStatus}>Refresh</button>
        </div>
      </div>

      {/* View Toggle */}
      <div style={{ display: 'flex', gap: '1rem', marginBottom: '1.5rem' }}>
        <button 
          className={`btn ${view === 'status' ? '' : 'btn-secondary'}`} 
          onClick={() => setView('status')}
          style={{ flex: 1 }}
        >
          Today's Status
        </button>
        <button 
          className={`btn ${view === 'logs' ? '' : 'btn-secondary'}`} 
          onClick={() => setView('logs')}
          style={{ flex: 1 }}
        >
          Attendance Logs
        </button>
      </div>

      {/* Today's Summary Stats (status view only) */}
      {view === 'status' && !loading && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}>
          <div className="card" style={{ textAlign: 'center', padding: '1rem' }}>
            <div style={{ fontSize: '2rem', fontWeight: 800, color: 'var(--success)' }}>{presentCount}</div>
            <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>✅ Present Today</div>
          </div>
          <div className="card" style={{ textAlign: 'center', padding: '1rem' }}>
            <div style={{ fontSize: '2rem', fontWeight: 800, color: 'var(--danger)' }}>{absentCount}</div>
            <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>❌ Absent Today</div>
          </div>
          <div className="card" style={{ textAlign: 'center', padding: '1rem' }}>
            <div style={{ fontSize: '2rem', fontWeight: 800, color: 'var(--primary)' }}>
              {dailyStatus.length > 0 ? Math.round((presentCount / dailyStatus.length) * 100) : 0}%
            </div>
            <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>📊 Attendance Rate</div>
          </div>
        </div>
      )}

      {/* Filters Card */}
      <div className="card" style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          {/* Search */}
          <div style={{ flex: 1, minWidth: '220px', position: 'relative' }}>
            <Search size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
            <input 
              type="text" 
              placeholder="Search by name..." 
              className="form-control"
              style={{ paddingLeft: '2.5rem' }}
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          {/* Date filter (logs only) */}
          {view === 'logs' && (
            <div style={{ width: '200px' }}>
              <input 
                type="date" 
                className="form-control"
                value={dateFilter}
                onChange={(e) => setDateFilter(e.target.value)}
              />
            </div>
          )}

          {/* Branch Filter */}
          {branches.length > 0 && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap' }}>
              <MapPin size={15} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />
              <button
                onClick={() => setBranchFilter('all')}
                style={{
                  padding: '0.3rem 0.85rem', borderRadius: '999px', fontSize: '0.8rem', fontWeight: 600, cursor: 'pointer', border: '1px solid',
                  background: branchFilter === 'all' ? 'var(--primary)' : 'transparent',
                  color: branchFilter === 'all' ? '#fff' : 'var(--text-muted)',
                  borderColor: branchFilter === 'all' ? 'var(--primary)' : 'var(--border)',
                  transition: 'all 0.2s'
                }}
              >
                All
              </button>
              {branches.map(b => (
                <button
                  key={b}
                  onClick={() => setBranchFilter(b)}
                  style={{
                    padding: '0.3rem 0.85rem', borderRadius: '999px', fontSize: '0.8rem', fontWeight: 600, cursor: 'pointer', border: '1px solid',
                    background: branchFilter === b ? 'var(--primary)' : 'transparent',
                    color: branchFilter === b ? '#fff' : 'var(--text-muted)',
                    borderColor: branchFilter === b ? 'var(--primary)' : 'var(--border)',
                    transition: 'all 0.2s'
                  }}
                >
                  {b}
                </button>
              ))}
            </div>
          )}
        </div>
      </div>

      <div className="card">
        <div className="table-container">
          <table className="data-table">
            <thead>
              {view === 'logs' ? (
                <tr>
                  <th>Date</th>
                  <th>Employee</th>
                  <th>Role</th>
                  <th>Branch</th>
                  <th>Department</th>
                  <th>Clock-In Time</th>
                </tr>
              ) : (
                <tr>
                  <th>Employee</th>
                  <th>Role</th>
                  <th>Branch</th>
                  <th>Department</th>
                  <th>Today's Status</th>
                  <th>Clock-In Time</th>
                </tr>
              )}
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan={6} style={{ textAlign: 'center', padding: '3rem' }}>Loading...</td></tr>
              ) : filteredData.length === 0 ? (
                <tr><td colSpan={6} style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-muted)' }}>No records found.</td></tr>
              ) : filteredData.map((item, idx) => (
                <tr key={idx}>
                  {view === 'logs' ? (
                    <>
                      <td>{new Date(item.date).toLocaleDateString()}</td>
                      <td>
                        <div style={{ fontWeight: 600 }}>{item.employee_name}</div>
                      </td>
                      <td>{item.employee_role.toUpperCase()}</td>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', fontSize: '0.85rem' }}>
                          <MapPin size={12} style={{ color: 'var(--primary)', flexShrink: 0 }} />
                          {item.branch || '—'}
                        </div>
                      </td>
                      <td>{item.department}</td>
                      <td>{item.created_at ? new Date(item.created_at).toLocaleTimeString() : 'N/A'}</td>
                    </>
                  ) : (
                    <>
                      <td>
                        <div style={{ fontWeight: 600 }}>{item.name}</div>
                      </td>
                      <td>{item.employee_role.toUpperCase()}</td>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', fontSize: '0.85rem' }}>
                          <MapPin size={12} style={{ color: 'var(--primary)', flexShrink: 0 }} />
                          {item.branch || '—'}
                        </div>
                      </td>
                      <td>{item.department}</td>
                      <td>
                        <span className={`badge ${item.status === 'Present' ? 'success' : 'danger'}`}>
                          {item.status}
                        </span>
                      </td>
                      <td>{item.clock_in_time ? new Date(item.clock_in_time).toLocaleTimeString() : '-'}</td>
                    </>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default AttendanceManagement;
